-- Revert added defaults (best-effort)
ALTER TABLE years
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE companies
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE yearly_companies
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE sponsorship_contracts
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE sponsorship_menus
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE contract_menus
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE payments
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE assignments
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE activity_logs
  MODIFY COLUMN created_at DATETIME NOT NULL;

ALTER TABLE users
  MODIFY COLUMN created_at DATETIME NOT NULL,
  MODIFY COLUMN updated_at DATETIME NOT NULL;
