-- Add DEFAULT CURRENT_TIMESTAMP to created_at/updated_at columns and normalize existing zero dates
SET @now := CURRENT_TIMESTAMP();

-- Normalize and set defaults for tables
ALTER TABLE years
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE years SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE companies
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE companies SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE yearly_companies
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE yearly_companies SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE sponsorship_contracts
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE sponsorship_contracts SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE sponsorship_menus
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE sponsorship_menus SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE contract_menus
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE contract_menus SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE payments
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE payments SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE assignments
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE assignments SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE activity_logs
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE activity_logs SET created_at = @now WHERE YEAR(created_at) = 0;

ALTER TABLE users
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE users SET created_at = @now WHERE YEAR(created_at) = 0;
